input_dir: "/data"
# Run dir pattern with {input_dir}.
run_dir_pattern: "20[2-9][0-9]{5}[^/]+"
# Output dir with {input_dir}/{run_dir}/*/*/pod5/
# Can use {run_dir}, {subrun_dir}, and {flowcell} wildcards.
run_output_dir: "/data/{run_dir}/{subrun_dir}/{flowcell}/pod5/basecalling"
# Directory for checkpoints. If contains sha256 hash of {run_dir}_{subrun_dir}_{flowcell}, skips it.
run_chkpt_dir: "complete"

# Dorado settings.
dorado:
  bin: "/opt/logsdon_lab/dorado-1.1.1-linux-x64/bin/dorado"
  model: "sup"
  min_qscore: 0
  modifications: "5mC_5hmC"
  devices: "all"
  duplex: true
